### ISSUE TITLE
The default Javascript scripts folder on Windows

### ISSUE THREAD

**Issue by mstuyts** [north-road/qgis-processing-js#4]
After installation of the plugin the default Javascript scripts folder in the Options|Processing window is:
C:\Users\myusername\AppData\Roaming\QGIS\QGIS3\profiles\default\processing\scripts

The following folder also exists:
C:\Users\myusername\AppData\Roaming\QGIS\QGIS3\profiles\default\processing\jsscripts

This jsscripts folder probably should be the default Javascript scripts folder.

**Comment by nyalldawson** [comment]
I can't reproduce this -- I've tried a clean install on a new profile, and the default path shown in Options-Processing is "....\jsscripts". Do you see this on the current version, on a clean profile?

**Comment by mstuyts** [comment]
I tried it again on a different PC.  When installing the plugin in my existing profile the default Javascript scripts folder is: C:\Users\myusername\AppData\Roaming\QGIS\QGIS3\profiles\default\processing\scripts

When installing the plugin in a new profile the default Javascript scripts folder is: C:\Users\myusername\AppData\Roaming\QGIS\QGIS3\profiles\default\processing\jsscripts

I guess it's some interference by another installed plugin.  I have the following plugins installed:

- Another DXF Importer / DXF2Shape Converter
- Attribute painter
- changeDataSource *
- Concave Hull *
- Contour plugin
- Coordinate Capture
- DB Manager *
- Digitizing Tools
- Dot Map
- eVis
- ExamplePlugin
- First Aid
- Freehand raster georeferencer
- Geometry Checker
- Geometry Paster *
- geopunt4Qgis
- Georeferencer GDAL *
- go2mapillary
- go2streetview
- GPS Tools
- Grass 7
- GxABT - FixLambert72
- Instant Print
- KML Tools
- Label2Attr
- LAStools
- Layer From Clipboard
- Layers menu from project *
- Layout Loader *
- MetaSearch Catalog Client
- mmqgis *
- Offline Editing
- pickLayer
- Plugin Load Times *
- Plugin Reloader *
- prepair for Processing *
- Processing *
- Processing Javascript Provider *
- QGIS Hats *
- QGIS Network Logger *
- qgis2web
- QPackage
- Quick Attribution
- QuickCRS
- QuickMapServices *
- QuickOSM
- QuickPrint
- Raster Transparency
- Remote Debug
- Select Within
- Swap Vector Direction
- TimeManager
- web2qgis
- Topology Checker
- web2qgis
- Whitebox for Processing *
- ZoomToBelgium *

Plugins with an * are enabled

**Comment by nyalldawson** [comment]
Thanks, that's helped me track this down!
